National Costume: Barot Saya - Barot saya is a sophisticated fusion of Spanish and Filipino design.
National Anthem: “Lupang Hinirang” - Julian Felipe wrote the "Lupang Hinirang" national hymn for the Philippines. During the declaration of Philippine Independence on June 12, 1898, "Lupang Hinirang" was first heard in public. The Spanish poem Filipinas by José Palma served as the inspiration for its lyrics.
National Flower: Sampaguita - The "sampaguita" flower, also known as the Arabian jasmine, is the national flower of the Philippines. Its hue, white, stands for strength, simplicity, humility, and purity.
National Tree: Narra - The "narra" or rosewood tree is the official national tree of the Philippines.
National Bird: Philippine Eagle - The Philippine national bird is called the “Philippine eagle”  scientifically known as Pithecophaga jefferyi
National Sport: Arnis - Arnis is sometimes referred to as Kali and Eskrima. This activity encourages stick-based combat using a variety of improvised weapons. It also teaches techniques for fighting with your hands, grabbing, and disarming weapons.
National Hero: Dr. Jose Rizal - Dr. Jose Protacio Rizal Mercado y Alonzo Realonda's or Dr. Jose P. Rizal was our national hero because he battled for independence through his writings and words.
National Leaf: Anahaw - The national leaf of the Philippines is Anahaw. This leaf may be used for a variety of purposes. It can act as the Bahay-Kubo or nipa hut's roof. This leaf may also be used to create hats, backpacks, and fans.
National Fruit: Mango - The Philippines' fleshy, sweet, golden, delectable, and juicy mango fruit may be eaten and prepared in a variety of ways. Mango may be used as the main component in desserts.
National Animal: Carabao - The national animal of the Philippines, the Carabao, symbolizes the people's tenacity and resilience. It also goes by the moniker "the farmer's best friend."
National Fish: Bangus - Bangus, commonly referred to as milkfish, was the national fish of the Philippines. It is infamous for having a bonier and fatty tummy. It is readily accessible in the nation and may be used to prepare a broad variety of cuisines.
National Dance: Cariñosa - Cariosa is the national dance of the Philippines. Folk dance including the Maria Clara suite exemplifies the modest manners and demeanor of Filipina ladies. It is also referred to as the dance's depiction of courting and devotion.
National dress Barong Tagalog - is an embroidered long-sleeved formal shirt for men and a national dress of the Philippines. Barong tagalog combines elements from both the precolonial native Filipino and colonial Spanish clothing styles
ASWANG - They are thought to be evil creatures that eat their victims' flesh and blood. They look like regular people, but at night they turn into an animal, usually a dog, with superhuman power and speed.
DIWATA - The diwata are a species of fairy who are revered as gods and protectors of nature. They help the deserving and severely punish those who take advantage of them or destroy their country.
TIYANAK - a monster that pretends as a sobbing child. When it is picked up, it changes into a little, horrifying monster with razor-sharp fangs and superhuman power that mauls and devours its prey.
TAMBAL - The tambal, a monster that can alter its appearance to that of its human prey, is the equivalent of the doppelganger in Filipino culture. They make their victims go lost for days and then take up residence in their house where they mingle with family and friends.
KAPRE - is a legendary monster that is often seen smoking at the top of trees and is referred to as a tree giant because of its enormous, black, and hairy build.
TIKBALANG - a huge beast with a man's body and a horse's head. The fabled monster would lead tourists astray in the woods since it is frequently mischievous. However, some practical jokes take a serious turn and send individuals insane.
DUWENDE - They look like little elderly guys who are selective about whom they reveal themselves. According to legend, if a friendly duwende resides in your home, you will lead a happy and successful life.
SINULOG - In commemoration of the statue of the Santo  Niño or the Child Jesus, the Sinulog Festival is celebrated in the city of Cebu.
ATI - ATIHAN - Aside from Boracay Island's beaches and waterways, Aklan receives a lot of visitors in January because of the Ati-Atihan Festival, which is also held in honor of the Santo Niño.
PANAGBENGA - The Panagbenga flower festival is held every year in Baguio. The Kankanaey name panagbenga, which means "blooming season," denotes this.
KADAYAWAN - In the city of Davao, there is a significant festival of thanksgiving called the Kadayawan Festival.
PAHIYAS - Nothing is more colorful than the Pahiyas Festival in Lucban as each house competes to showcase the best decorated kiping (wafer made from glutinous rice). The festival is celebrated as a form of thanksgiving for a year of a good harvest.
SANTACRUZAN - festivals in May, with pagan origins but portraying strong Christian symbols
JUAN TAMAD - This well-known children's tale centers on a boy who is so incredibly lazy that he engages in foolish behavior that leads to problems simply because he lacks the motivation to do anything.
IBONG ADARNA - This well-known fable is included in Filipino high school textbooks in the Philippines. Ibong Adarna is a story about a "eponymous magical bird" that three princes are trying to find because it can heal the sick king but is hard to find.
SI PAGONG AT SI MATSING - Si Pagong at si Matsing, one of the most well-known children's tales, tells the tale of how the giving and gentle tortoise outwitted the greedy monkey over a banana tree.
ANG ALAMAT NG PINYA - The fable of the pineapple tells the tale of Pina, a spoiled young girl. Pina was ordered to look for a ladle when her mother was unwell, but she was too lazy to ask for assistance. Pina vanished shortly after, leaving her mother furious and wishing she had a thousand eyes so she could see it. After that, her mother discovered a fruit that was covered in unseen eyes, giving rise to the pineapple mythology. 
BAYANIHAN - The term "bayanihan," which is a combination of the words "bayan," which means "community," and "bayani," which means "heroes," refers to the phenomena that occurs when Filipinos band together to provide heroic deeds for those in need without asking anything in return. Helping others, even complete strangers, without being asked is entrenched in Philippine culture.
PAGMAMANO - Young Filipinos frequently display the "pagmamano" gesture as a sign of respect for the elders. With his or her right hand, the older lightly taps the young person on the forehead to accomplish this. 
PO AT OPO - In addition to pagmamano, the terms po and opo are used by Filipinos to express respect while speaking to seniors or other deserving individuals. When used as a contraction, po, apo is a polite way to punctuate or end a phrase.
JEEPNEY - Jeepneys are a well-known symbol of Filipino culture and have played a crucial role in the country's transportation system for more than 70 years. These brilliant, colorful vehicles have become a significant component of Filipino culture and have been depicted in a variety of works of art, including paintings.
SABONG - Cockfighting is a common practice in the Philippines, despite the fact that it may look barbaric to outsiders. These meticulously nurtured birds are held to be the fate of hopes, dreams, and fortunes.
PANLILIGAW - The courting methods used in the Philippines to entice people are still referred to as old-fashioned. Courting is typically a respectable and courteous manner for young boys and girls to get to know one other without any hanky-panky involved because Catholic women are supposed to remain virgins until marriage.
PAKIKIPAGKAPWA-TAO - is to treasures relationships, with friends and strangers alike. It is also one of the oldest and strongest Filipino values.
KALESA - a two-wheeled horse-drawn carriage used in the Philippines. It was a primary mode of public and private transportation during the Spanish colonial era of the Philippines, though in modern times, they largely only survive as tourist attractions
MALONG -  a colourful woven tube of cloth that can be worn in a variety of ways by both men and women, is characteristic of Muslim communities in Mindanao.
ESPASOL - This dish is a Laguna province favorite and a favorite Filipino delicacy. Espasol consists of coconut and glutinous rice strips that have been dusted with toasted flour.
YEMA - Yema is a popular custard candy in the Philippines. The only ingredients you'll ever need to make this sweet and creamy triangle confection are egg yolks, butter, and condensed milk.
PASTILLAS DE LECHE - Spanish for "milk tablets," pastillas de leche are a sweet treat made of evaporated milk and dusted with sugar. It typically arrives in bundles that have been wrapped in vibrant Japanese sheets.
OTAP - Popular puff pastry from Cebu, Philippines, is called otap. This coconut and flour pastry is sweet and flaky, and it's baked to perfection with sugar sprinkles on top.
BARQUILLOS - Barquillos are a type of wafer roll snack that is well-liked outside of the Philippines. This crunchy roll comes in a variety of flavors, including ube and pandan.
MACAPUNO - This sugary ball is referred to as a macapuno candy. You'll need macapuno preserves, cornstarch, water, and condensed milk to make a macapuno candy.
PICHI - PICHI - You must taste this delicious gelatinous treat made from cassava and sugar. Typically, grated coconut and cheese are sprinkled on top of this sweet treat to add taste.
POLVORON - This powdery treat is a preferred Filipino memento, especially considering how simple it is to create. The only ingredients are toasted flour, powdered milk, and sugar, making it a delightful little snack to enjoy with every merienda.
LAMBANOG - is a traditional Filipino distilled coconut palm liquor. It was also known as vino de coco in Spanish
BALUT -  a parboiled embryonic duck still in the egg, is a popular street food in the Manila area.
KULINTANG -  in some of the Muslim communities of Mindanao and the Sulu Archipelago, the kulintang ensemble, consisting of a set of gongs suspended horizontally and vertically and a single-headed drum, can still be heard at festive events.
ANITOS - early Spanish chroniclers testified that the Filipinos carved the images of their anitos (gods and goddesses) and ancestors in wood
DARANGEN - depicts the historical and mythological world of the Maranao community
